apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-egress-airflow-worker
  namespace: team-knada-hyka
spec:
  egress:
  - ports:
    - port: 80
      protocol: TCP
    to:
    - ipBlock:
        cidr: 169.254.169.254/32 # metadata server (for workload identity)
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 140.82.112.0/20 # github (clone repo with dags)
    - ipBlock:
        cidr: 173.194.0.0/16 # storage.googleapis.com (for log write) 
    - ipBlock:
        cidr: 66.102.0.0/20 # storage.googleapis.com (for log write)
    - ipBlock:
        cidr: 74.125.0.0/16 # storage.googleapis.com (for log write)
    - ipBlock:
        cidr: 64.233.160.0/19 # storage.googleapis.com (for log write)
    - ipBlock:
        cidr: 142.250.0.0/15 # storage.googleapis.com (for log write)
    - ipBlock:
        cidr: 100.68.0.1/32 # api server (necessary for KubernetesPodOperators)
    - ipBlock:
        cidr: 172.16.0.2/32 # api server (necessary for KubernetesPodOperators)
  - ports: # dns
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - ports: # airflow db
    - port: 5432
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: cloudsql-proxy
  podSelector:
    matchLabels:
      component: worker
      release: airflow
  policyTypes:
  - Egress
