apiVersion: apps/v1
kind: Deployment
metadata:
  name: knetpoller
  namespace: knada-system
  labels:
    app: knetpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knetpoller
  template:
    metadata:
      labels:
        app: knetpoller
    spec:
      serviceAccountName: knetpoller
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: knetpoller
        image: europe-west1-docker.pkg.dev/knada-gcp/knetpoller/knetpoller
