apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: knetpoller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: knetpoller
    app.kubernetes.io/part-of: knetpoller
    app.kubernetes.io/managed-by: kustomize
  name: knetpoller
  namespace: knada-system
