apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knep
  namespace: knada-system
  labels:
    app.kubernetes.io/name: knep
spec:
  dnsNames:
  - 'knep.knada-system.svc'
  issuerRef:
    kind: Issuer
    name: knep
  secretName: knep-webhook-server-cert
