apiVersion: apps/v1
kind: Deployment
metadata:
  name: knep
  namespace: knada-system
  labels:
    app.kubernetes.io/name: knep
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knep
    spec:
      serviceAccountName: knep
      containers:
      - name: knep
        ports:
        - containerPort: 9443
        env:
          - name: BIGQUERY_PROJECT
            value: nada-prod-6977
          - name: BIGQUERY_DATASET
            value: knep
          - name: BIGQUERY_TABLE
            value: allowlist_historic
        image: ghcr.io/navikt/knada-images/test-image:v32
        volumeMounts:
          - name: webhook-server-cert
            mountPath: /run/secrets/tls
            readOnly: true
      volumes:
        - name: webhook-server-cert
          secret:
            secretName: knep-webhook-server-cert
