apiVersion: apps/v1
kind: Deployment
metadata:
  name: knep
  namespace: knada-system
  labels:
    app.kubernetes.io/name: knep
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knep
    spec:
      serviceAccountName: knep
      containers:
      - name: knep
        ports:
        - containerPort: 9443
        env:
          - name: BIGQUERY_PROJECT
            value: nada-prod-6977
          - name: BIGQUERY_DATASET
            value: knep
          - name: BIGQUERY_TABLE
            value: allowlist_historic
          - name: CERT_PATH
            value: /run/secrets/tls
        image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knep
        volumeMounts:
          - name: webhook-server-cert
            mountPath: /run/secrets/tls
            readOnly: true
          - name: onprem-firewall-map 
            mountPath: "/var/run"
      volumes:
        - name: webhook-server-cert
          secret:
            secretName: knep-webhook-server-cert
        - name: onprem-firewall-map
          configMap:
            name: onprem-firewall-map
