apiVersion: apps/v1
kind: Deployment
metadata:
  name: knep
  namespace: knada-system
  labels:
    app.kubernetes.io/name: knep
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: knep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knep
    spec:
      serviceAccountName: knep
      nodeSelector:
        knada-infrastructure: ""
      tolerations:
        - key: "knada-infrastructure"
          effect: "NoSchedule"
          operator: "Exists"
      containers:
      - name: knep
        ports:
        - containerPort: 9443
        env:
          - name: BIGQUERY_PROJECT
            value: <placeholder>
          - name: BIGQUERY_DATASET
            value: knep
          - name: BIGQUERY_TABLE
            value: allowlist_historic
          - name: CERT_PATH
            value: /run/secrets/tls
          - name: ONPREM_HOSTMAP_FILE
            value: /var/run/onprem-hosts.yaml
          - name: EXTERNAL_HOSTMAP_FILE
            value: /var/run/external-hosts.yaml
        image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knep
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
          - name: webhook-server-cert
            mountPath: /run/secrets/tls
            readOnly: true
          - name: onprem-firewall-map 
            mountPath: /var/run/onprem-hosts.yaml
            subPath: onprem-hostmap.yaml
          - name: external-hosts-map 
            mountPath: /var/run/external-hosts.yaml
            subPath: external-hosts.yaml
      volumes:
        - name: webhook-server-cert
          secret:
            secretName: knep-webhook-server-cert
        - name: onprem-firewall-map
          configMap:
            name: onprem-hostmap
        - name: external-hosts-map
          configMap:
            name: knep-external-hosts-map
