apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: knep
  annotations:
    cert-manager.io/inject-ca-from: knada-system/knep
webhooks:
  - name: knep.knada-system.svc
    namespaceSelector:
      matchExpressions:
        - key: team-namespace
          operator: Exists
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions: 
    - v1
    clientConfig:
      service:
        name: knep
        namespace: knada-system
        path: "/admission"
    rules:
      - operations: ["CREATE","DELETE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
